const ADMIN_GET_LIST = 'ADMIN_GET_LIST'
const ADMIN_ADD = 'ADMIN_ADD'
const ADMIN_MODIFY = 'ADMIN_MODIFY'
const ADMIN_REGISTER = 'ADMIN_REGISTER'
const ADMIN_SIGNIN = 'ADMIN_SIGNIN'
const ADMIN_ISSIGNIN = 'ADMIN_ISSIGNIN'
const ADMIN_SIGOUT = 'ADMIN_SIGOUT'
const ADMIN_MODIFYPWD = 'ADMIN_MODIFYPWD'
export default {
	ADMIN_GET_LIST,
	ADMIN_ADD,
	ADMIN_MODIFY,
	ADMIN_REGISTER,
	ADMIN_SIGNIN,
	ADMIN_ISSIGNIN,
	ADMIN_SIGOUT,
	ADMIN_MODIFYPWD,
}

