const ALERT_SHOW_SUCCESS = 'ALERT_SHOW_SUCCESS'
const ALERT_SHOW_WARNING = 'ALERT_SHOW_WARNING'
const ALERT_SHOW_DANGER = 'ALERT_SHOW_DANGER'
const ALERT_SHOW_INFO = 'ALERT_SHOW_INFO'

const ALERT_SHOW_SUCCESS_AUTO = 'ALERT_SHOW_SUCCESS_AUTO'
const ALERT_SHOW_WARNING_AUTO = 'ALERT_SHOW_WARNING_AUTO'
const ALERT_SHOW_DANGER_AUTO = 'ALERT_SHOW_DANGER_AUTO'
const ALERT_SHOW_INFO_AUTO = 'ALERT_SHOW_INFO_AUTO'

const ALERT_CLOSE = 'ALERT_CLOSE'

export default {
	ALERT_SHOW_SUCCESS,
	ALERT_SHOW_WARNING,
	ALERT_SHOW_DANGER,
	ALERT_SHOW_INFO,
	ALERT_SHOW_SUCCESS_AUTO,
	ALERT_SHOW_WARNING_AUTO,
	ALERT_SHOW_DANGER_AUTO,
    ALERT_SHOW_INFO_AUTO,
    ALERT_CLOSE,
}

